export const LOGIN_SUCCESS = 'USER.LOGIN_SUCCESS';
export const LOGIN_FAILED = 'USER.LOGIN_FAILED';

export const SIGNOUT = 'USER.SIGNOUT';

export const SET_USER = 'USER.SET_USER';

export const UPDATE_IMAGE = 'USER.UPDATE_IMAGE';
export const SAVE_PROFILE_INFO = 'USER.SAVE_PROFILE_INFO';
export const SAVE_PERSONA_INFO = 'USER.SAVE_PERSONA_INFO';

export const FILL_USER_PROFILE = 'USER.FILL_USER_PROFILE';

export const UPDATE_PROFILE_INFO = 'USER.UPDATE_PROFILE_INFO';
export const UPDATE_INVESTOR_PROFILE = 'USER.UPDATE_INVESTOR_PROFILE';

export const CHECK_USER_STATUS = 'USER.CHECK_USER_STATUS';